# Generated by Django 5.0.6 on 2024-05-20 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название отеля')),
                ('description', models.TextField(blank=True, verbose_name='Описание отеля')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('contacts', models.TextField(blank=True, null=True, verbose_name='Контакты')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Рейтинг')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('allow_check_in_time', models.TimeField(blank=True, null=True, verbose_name='Доступное время заезда')),
                ('allow_check_out_time', models.TimeField(blank=True, null=True, verbose_name='Доступное время выезда')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, verbose_name='Номер комнаты')),
                ('room_type', models.CharField(choices=[('single', 'Одиночный'), ('double', 'Двухместный'), ('triple', 'Трёхместный'), ('quadruple', 'Четырёхместный')], max_length=100, verbose_name='Тип комнаты')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь')),
                ('availability', models.BooleanField(default=True, verbose_name='Доступность')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_reservations.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['hotel', 'room_number'],
            },
        ),
    ]
